[project]
name = "teeb"
version = "0.1.0"
description = "Simple music album pre-tagging cleaner."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chardet",
    "send2trash",
    "wand",
]

[dependency-groups]
dev = [
    "behave",
    "ipdb",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "ruff",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
pythonpath = [
  "src"
]
testpaths = [
    "tests",
]

[tool.basedpyright]
include = ["src"]
exclude = [
    "**/__pycache__",
]
executionEnvironments = [
  { root = "src/tests", reportPrivateUsage = false, extraPaths = ["src/tests/e2e", "src/sdk" ]},
  { root = "src" }
]
