[project]
name = "teeb"
version = "0.1.0"
description = "Simple music album pre-tagging cleaner."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chardet",
    "pre-commit",
    "ruff",
    "send2trash",
    "wand",
]

[dependency-groups]
dev = [
    "behave",
    "ipdb",
    "pytest",
    "pytest-cov",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
pythonpath = [
  "src"
]
testpaths = [
    "tests",
]
